name:                 collatz-conjecture
version:              1.2.1.4
visibility:           public
id:                   collatz-conjecture-1.2.1.4-1SiTXl6COMw1VzV1nJTyLD
key:                  collatz-conjecture-1.2.1.4-1SiTXl6COMw1VzV1nJTyLD
abi:                  ca111909e8636904a679cdb250ca44ea
exposed:              True
exposed-modules:      CollatzConjecture
hidden-modules:       Paths_collatz_conjecture
import-dirs:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/lib/aarch64-osx-ghc-9.2.7/collatz-conjecture-1.2.1.4-1SiTXl6COMw1VzV1nJTyLD

library-dirs:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/lib/aarch64-osx-ghc-9.2.7/collatz-conjecture-1.2.1.4-1SiTXl6COMw1VzV1nJTyLD

dynamic-library-dirs:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/lib/aarch64-osx-ghc-9.2.7

data-dir:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/share/aarch64-osx-ghc-9.2.7/collatz-conjecture-1.2.1.4

hs-libraries:         HScollatz-conjecture-1.2.1.4-1SiTXl6COMw1VzV1nJTyLD
depends:              base-4.16.4.0
haddock-interfaces:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/doc/collatz-conjecture-1.2.1.4/collatz-conjecture.haddock

haddock-html:
    /Users/ajayliu/Exercism/haskell/collatz-conjecture/.stack-work/install/aarch64-osx/c587f58783953e4839c2b816d3fba6e41b63e8fc868d57ac19555bbc8c2850f3/9.2.7/doc/collatz-conjecture-1.2.1.4
